export const CATEGORIES = ["All", "Shirts", "Trousers", "Kurtas", "Sarees", "Fabrics"];

export const SORT_OPTIONS = [
  { value: "featured", label: "Featured" },
  { value: "price-asc", label: "Price: Low–High" },
  { value: "price-desc", label: "Price: High–Low" },
  { value: "rating", label: "Top Rated" },
];

export const TRUST_ITEMS = [
  { icon: "🧵", title: "Artisan Crafted", desc: "Handloom & block print traditions" },
  { icon: "🚚", title: "Free Shipping", desc: "On orders above ₹1,999" },
  { icon: "↩️", title: "Easy Returns", desc: "14-day hassle-free policy" },
  { icon: "💳", title: "Secure Payment", desc: "Encrypted & PCI compliant" },
];

export const FOOTER_LINKS = ["Privacy", "Terms", "Support"];

export const PRODUCTS = [
  {
    // ── Store fields ──────────────────────────────────────────────
    id: "handloom-cotton-shirt",
    name: "Handloom Cotton Shirt",
    category: "Shirts",
    price: 1299,
    originalPrice: 1799,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80",
    rating: 4.5,
    reviews: 128,
    badge: "Bestseller",
    inStock: true,
    colors: ["#f5f0eb", "#4a3728", "#2d4a3e"],
    material: "100% Handloom Cotton",
    // ── Product page fields ───────────────────────────────────────
    type: "Apparel",
    tagline: "Naturally woven, effortlessly worn — crafted for everyday comfort.",
    description:
      "This handloom cotton shirt is woven on traditional pit looms by skilled artisans in rural Andhra Pradesh. Each thread is hand-spun, giving the fabric a uniquely textured, breathable finish that only improves with every wash. Perfect for both casual and semi-formal settings.",
    highlights: [
      "Hand-spun 100% cotton yarn for superior breathability",
      "Traditional pit-loom weaving technique",
      "Natural dyes — safe for skin and environment",
      "Pre-washed for minimal shrinkage",
      "Available in 3 earthy tones",
      "Machine washable at 30°C",
    ],
    forWho: ["Daily Wear", "Casual Office", "Gifting", "Eco-conscious Shoppers"],
    details: {
      format: "Ready to Wear",
      fabric: "100% Handloom Cotton",
      weight: "180 GSM",
      fit: "Regular Fit",
      care: "Machine Wash 30°C",
      origin: "Andhra Pradesh, India",
    },
    variants: [
      { id: "regular", label: "Regular Fit" },
      { id: "slim", label: "Slim Fit" },
    ],
    faqs: [
      {
        q: "Will the shirt shrink after washing?",
        a: "It has been pre-washed to minimise shrinkage. We recommend washing at 30°C to keep the fabric in its best shape.",
      },
      {
        q: "Are the dyes safe for sensitive skin?",
        a: "Yes, only OEKO-TEX certified natural dyes are used — free from harmful chemicals.",
      },
      {
        q: "Can I return if the size doesn't fit?",
        a: "Absolutely. We offer a 14-day hassle-free return and size exchange policy.",
      },
    ],
  },
  {
    id: "linen-kurta-sage",
    name: "Linen Kurta — Sage",
    category: "Kurtas",
    price: 1849,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    rating: 4.8,
    reviews: 94,
    badge: "New",
    inStock: true,
    colors: ["#8faf8f", "#c4b5a0", "#3d3d3d"],
    material: "Pure Linen",
    type: "Kurta",
    tagline: "Clean lines, quiet luxury — the everyday kurta, elevated.",
    description:
      "Cut from premium Belgian linen, the Sage Kurta offers a relaxed silhouette with subtle structure. Its sage green hue is achieved through a low-impact reactive dye process. Designed for warm climates, this kurta breathes exceptionally well and drapes beautifully across all body types.",
    highlights: [
      "Belgian linen with 30% lower water footprint",
      "Low-impact reactive sage dye",
      "Relaxed yet structured silhouette",
      "Mother-of-pearl buttons at collar",
      "Side slits for ease of movement",
      "Wrinkle-resistant finish",
    ],
    forWho: ["Ethnic Occasions", "Work from Home", "Festive Wear", "Minimalist Dressers"],
    details: {
      format: "Ready to Wear",
      fabric: "Pure Belgian Linen",
      weight: "145 GSM",
      fit: "Relaxed Fit",
      care: "Hand Wash / Dry Clean",
      origin: "Jaipur, Rajasthan",
    },
    variants: [
      { id: "half-sleeve", label: "Half Sleeve" },
      { id: "full-sleeve", label: "Full Sleeve" },
    ],
    faqs: [
      {
        q: "Does linen wrinkle easily?",
        a: "Linen naturally creases but this fabric has a wrinkle-resistant finish. Light ironing on medium heat restores a crisp look.",
      },
      {
        q: "Is this suitable for summer?",
        a: "Absolutely — linen is one of the most breathable natural fibres, making it ideal for warm and humid climates.",
      },
      {
        q: "What length does the kurta come in?",
        a: "The kurta falls at mid-thigh (approx. 40 inches). Custom lengths are available on request.",
      },
    ],
  },
  {
    id: "khadi-silk-saree",
    name: "Khadi Silk Saree",
    category: "Sarees",
    price: 4299,
    originalPrice: 5499,
    image: "https://images.unsplash.com/photo-1694610882150-4de206edf95a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a2hhZGklMjBzaWxrJTIwc2FyZWV8ZW58MHx8MHx8fDA%3D",
    rating: 4.7,
    reviews: 63,
    badge: "Limited",
    inStock: true,
    colors: ["#c9956a", "#8b5e3c", "#e8d5c4"],
    material: "Khadi Silk",
    type: "Saree",
    tagline: "Timeless handcraft — each saree is a one-of-a-kind heirloom.",
    description:
      "Woven on traditional handlooms in Murshidabad, West Bengal, this khadi silk saree blends the rustic character of khadi with the lustrous sheen of pure silk. Each piece is slightly unique — a testament to the human hands behind it. A limited-run collection that sells out fast.",
    highlights: [
      "Hand-spun khadi silk from Murshidabad",
      "Zari border with 22-carat gold thread",
      "6.3 metres including blouse piece",
      "Each piece is unique — minor variations expected",
      "Certificate of authenticity included",
      "Dry clean only for longevity",
    ],
    forWho: ["Festive Occasions", "Weddings", "Collectors", "Saree Connoisseurs"],
    details: {
      format: "6.3 metres + blouse piece",
      fabric: "Khadi Silk",
      weight: "420 GSM",
      border: "22-carat Zari",
      care: "Dry Clean Only",
      origin: "Murshidabad, West Bengal",
    },
    variants: [
      { id: "standard", label: "Standard (6.3m)" },
      { id: "extended", label: "Extended (8m)" },
    ],
    faqs: [
      {
        q: "Why does the saree look slightly different from the photo?",
        a: "Each saree is handwoven, so minor variations in colour and texture are natural and add to its uniqueness.",
      },
      {
        q: "Is the blouse piece included?",
        a: "Yes, a matching unstitched blouse piece of 0.8 metres is included with every saree.",
      },
      {
        q: "How should I store it?",
        a: "Wrap in a soft muslin cloth and store away from direct sunlight. Refold along different lines every 3–6 months to prevent crease damage.",
      },
    ],
  },
  {
    id: "slim-fit-linen-trouser",
    name: "Slim Fit Linen Trouser",
    category: "Trousers",
    price: 1599,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80",
    rating: 4.3,
    reviews: 211,
    badge: null,
    inStock: true,
    colors: ["#c4b5a0", "#3d3d3d", "#2d4a3e"],
    material: "Linen Blend",
    type: "Bottomwear",
    tagline: "Tailored comfort for the modern man — from desk to dinner.",
    description:
      "A slim-fit trouser crafted from a refined linen-cotton blend. Structured enough for a business-casual look, relaxed enough for a weekend out. Features a flat-front construction, two side pockets, and a back welt pocket — all finished with tonal stitching.",
    highlights: [
      "55% linen / 45% cotton blend for structure and breathability",
      "Flat-front slim-fit silhouette",
      "Tonal stitching throughout",
      "YKK zipper with hook-and-bar waistband closure",
      "Two side pockets + one back welt pocket",
      "Available in 3 versatile neutrals",
    ],
    forWho: ["Office Wear", "Smart Casual", "Travel", "Minimalist Style"],
    details: {
      format: "Ready to Wear",
      fabric: "55% Linen, 45% Cotton",
      weight: "210 GSM",
      fit: "Slim Fit",
      care: "Machine Wash 30°C",
      origin: "Tirupur, Tamil Nadu",
    },
    variants: [
      { id: "slim", label: "Slim Fit" },
      { id: "straight", label: "Straight Fit" },
    ],
    faqs: [
      {
        q: "Do the trousers have stretch?",
        a: "They don't have added elastane, but the linen-cotton blend has a natural give that allows comfortable movement.",
      },
      {
        q: "How do I pick the right size?",
        a: "Use our size guide on the product page. If you're between sizes, we recommend sizing up for linen blends.",
      },
      {
        q: "Will the colour fade after washing?",
        a: "We use reactive dyes that are wash-fast. Washing inside out in cold water will maximise colour longevity.",
      },
    ],
  },
  {
    id: "dobby-weave-fabric-roll",
    name: "Dobby Weave Fabric Roll",
    category: "Fabrics",
    price: 899,
    originalPrice: null,
    image: "https://plus.unsplash.com/premium_photo-1673481694721-6aa20c7c1c5c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZG9iYnklMjB3ZWF2ZSUyMGZhYnJpYyUyMHJvbGx8ZW58MHx8MHx8fDA%3D",
    rating: 4.6,
    reviews: 47,
    badge: "Bulk Deal",
    inStock: true,
    colors: ["#e8d5c4", "#4a3728", "#f5f0eb"],
    material: "Dobby Weave Cotton",
    type: "Fabric",
    tagline: "Premium by the metre — the fabric designers actually reach for.",
    description:
      "A tightly woven dobby cotton fabric with a subtle geometric texture. Priced per metre, it's favoured by independent designers, tailors, and boutique studios for its consistent quality and on-loom finish. Minimum order is 2 metres; bulk discounts apply at 10m+.",
    highlights: [
      "140cm wide — more usable width per metre",
      "Subtle dobby texture with geometric weave",
      "Pre-shrunk and colour-fast",
      "Suitable for shirts, kurtas, and light trousers",
      "Bulk discount at 10m+ orders",
      "Ships as a continuous roll",
    ],
    forWho: ["Tailors", "Fashion Designers", "Boutique Studios", "DIY Sewists"],
    details: {
      format: "Per Metre (min. 2m)",
      fabric: "100% Dobby Weave Cotton",
      weight: "160 GSM",
      width: "140 cm",
      care: "Machine Wash 40°C",
      origin: "Surat, Gujarat",
    },
    variants: [
      { id: "2m", label: "2 Metres" },
      { id: "5m", label: "5 Metres" },
      { id: "10m", label: "10 Metres (Bulk)" },
    ],
    faqs: [
      {
        q: "Is there a minimum order quantity?",
        a: "Yes, the minimum order is 2 metres. Bulk pricing kicks in at 10 metres.",
      },
      {
        q: "Can I get a sample before ordering in bulk?",
        a: "Yes — add a 0.25m sample swatch to your cart for ₹99 before committing to a larger order.",
      },
      {
        q: "Does the fabric come pre-washed?",
        a: "Yes, all fabric rolls are pre-washed and pre-shrunk so you can cut and sew directly.",
      },
    ],
  },
  {
    id: "block-print-cotton-kurta",
    name: "Block Print Cotton Kurta",
    category: "Kurtas",
    price: 1449,
    originalPrice: 1800,
    image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400&q=80",
    rating: 4.4,
    reviews: 156,
    badge: null,
    inStock: false,
    colors: ["#c9956a", "#f5f0eb", "#2d4a3e"],
    material: "Block Print Cotton",
    type: "Kurta",
    tagline: "Ancient craft, modern silhouette — hand-blocked by master printers.",
    description:
      "Each kurta is hand-printed using centuries-old wooden block printing techniques from Bagru, Rajasthan. No two pieces are identical. The natural indigo and rust dyes create rich, earthy tones that deepen beautifully with age. Currently out of stock — back in 2–3 weeks.",
    highlights: [
      "Hand-blocked with authentic Bagru wooden stamps",
      "Natural indigo and rust pigment dyes",
      "120-count pure cotton base fabric",
      "Each piece is genuinely unique",
      "Slightly irregular prints are a mark of authenticity",
      "Restocking in 2–3 weeks",
    ],
    forWho: ["Craft Enthusiasts", "Ethnic Occasions", "Gifting", "Art Collectors"],
    details: {
      format: "Ready to Wear",
      fabric: "120-count Pure Cotton",
      weight: "170 GSM",
      print: "Hand Block Print",
      care: "Cold Hand Wash",
      origin: "Bagru, Rajasthan",
    },
    variants: [
      { id: "regular", label: "Regular Fit" },
    ],
    faqs: [
      {
        q: "When will this be back in stock?",
        a: "We expect a fresh batch in 2–3 weeks. Join the waitlist to get notified the moment it's live.",
      },
      {
        q: "Why do the prints look slightly uneven?",
        a: "This is intentional. Slight variations and imperfections are the hallmark of genuine hand block printing — no machine can replicate this.",
      },
      {
        q: "Will the colours bleed in the first wash?",
        a: "Natural dyes may release a small amount of colour in the first wash. Always wash separately in cold water initially.",
      },
    ],
  },
  {
    id: "raw-silk-shirt",
    name: "Raw Silk Shirt",
    category: "Shirts",
    price: 2299,
    originalPrice: 2799,
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80",
    rating: 4.9,
    reviews: 38,
    badge: "Premium",
    inStock: true,
    colors: ["#c4b5a0", "#8faf8f", "#4a3728"],
    material: "Raw Silk",
    type: "Apparel",
    tagline: "The texture of luxury — raw silk with unmatched character.",
    description:
      "Cut from Tussar raw silk sourced directly from Jharkhand, this shirt carries a natural nubby texture that sets it apart from processed silks. The irregular slubs in the weave are a natural characteristic of Tussar silk — each shirt has its own visual personality. Tailored in a relaxed fit that works equally well dressed up or down.",
    highlights: [
      "100% Tussar raw silk from Jharkhand",
      "Natural slub texture — unique to each piece",
      "Mother-of-pearl buttons",
      "Relaxed fit with structured shoulders",
      "Double-stitched seams for durability",
      "Dry clean recommended; cold hand wash accepted",
    ],
    forWho: ["Premium Dressers", "Formal Occasions", "Wedding Guests", "Luxury Gifting"],
    details: {
      format: "Ready to Wear",
      fabric: "100% Tussar Raw Silk",
      weight: "95 GSM",
      fit: "Relaxed Fit",
      care: "Dry Clean / Cold Hand Wash",
      origin: "Bhagalpur, Jharkhand",
    },
    variants: [
      { id: "regular", label: "Regular Fit" },
      { id: "slim", label: "Slim Fit" },
    ],
    faqs: [
      {
        q: "What are the slubs in the fabric?",
        a: "Slubs are natural thickened spots in the silk yarn — they are not defects. They are the defining characteristic of authentic Tussar raw silk.",
      },
      {
        q: "Can I machine wash this shirt?",
        a: "We strongly recommend dry cleaning. If hand washing, use cold water with a silk-safe detergent and do not wring.",
      },
      {
        q: "Is this suitable for hot weather?",
        a: "Raw silk is lighter than you think at 95 GSM. It is comfortable in warm weather and can be layered in cooler months.",
      },
    ],
  },
  {
    id: "chikankari-silk-saree",
    name: "Chikankari Silk Saree",
    category: "Sarees",
    price: 6499,
    originalPrice: 7999,
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&q=80",
    rating: 5.0,
    reviews: 22,
    badge: "Artisan",
    inStock: true,
    colors: ["#f5f0eb", "#c9956a", "#3d3d3d"],
    material: "Chikankari Silk",
    type: "Saree",
    tagline: "300 years of embroidery tradition — worn for the moments that matter.",
    description:
      "Chikankari, the floral shadow embroidery of Lucknow, meets the drape of pure silk in this collector-grade saree. Each saree takes 3–4 weeks to complete — the embroidery alone requires 80+ hours by a master karigar. A piece that will be passed down through generations.",
    highlights: [
      "Pure organza silk base — lightweight and luminous",
      "80+ hours of hand Chikankari embroidery",
      "GI-tagged Lucknow Chikankari craft",
      "Floral motifs in white thread on ivory silk",
      "Comes with a hand-embroidered blouse piece",
      "Certificate of craft authenticity included",
    ],
    forWho: ["Weddings", "Special Occasions", "Heritage Collectors", "Luxury Gifting"],
    details: {
      format: "6.5 metres + blouse piece",
      fabric: "Pure Organza Silk",
      weight: "65 GSM",
      embroidery: "GI-tagged Lucknow Chikankari",
      care: "Dry Clean Only",
      origin: "Lucknow, Uttar Pradesh",
    },
    variants: [
      { id: "standard", label: "Standard (6.5m)" },
    ],
    faqs: [
      {
        q: "How long does it take to make one saree?",
        a: "Each saree takes 3–4 weeks to complete. The embroidery alone requires over 80 hours of work by a master karigar.",
      },
      {
        q: "Is the Chikankari work GI-tagged?",
        a: "Yes. Every saree comes with a GI certificate confirming authentic Lucknow Chikankari craft origin.",
      },
      {
        q: "What makes organza silk different from regular silk?",
        a: "Organza is woven from tightly twisted silk threads, giving it a crisp, lightweight, and semi-sheer quality — perfect for draping.",
      },
    ],
  },
];