import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/direction-3-premium/Layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Helper function to format page name from URL path
function getPageTitle(pathname) {
  // Remove leading slash and split
  const path = pathname.replace(/^\//, '').split('/');
  
  // If it's the home page or empty
  if (!path[0] || path[0] === '') {
    return 'Home';
  }
  
  // Get the last part of the path and format it
  const pageName = path[path.length - 1];
  
  // Capitalize and replace hyphens with spaces
  return pageName
    .replace(/-/g, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export const metadata = {
  title: {
    default: "Creator Studio",
    template: "%s | Creator Studio"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}